# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name:  Start npm
      working-directory: ./server
      run: |
        npm ci
        npm install
        npm run build --if-present
        npm i node-pre-gyp
        npm install canvas
  
  deploy:
    needs: [build]
    runs-on: self-hosted

    steps:
    - name: Deploy node app
      working-directory: ./server
      env:
        dsanalyzertoken: ${{ secrets.DS_ANALYZER_TOKEN }}
      run: pm2 restart index.js --name "village-analyzer" --node-args="--experimental-worker"
    

